# Generated by Django 4.1.1 on 2022-10-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_alter_vacancy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'permissions': [('can_publish', 'Может публиковать')], 'verbose_name': 'вакансия', 'verbose_name_plural': 'вакансии'},
        ),
    ]
