# Generated by Django 4.1.1 on 2022-10-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0006_advertisementtype_advertisement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
